DROP TABLE COURT_HEARING CASCADE CONSTRAINTS;
DROP TABLE EVIDENCE CASCADE CONSTRAINTS;
DROP TABLE OFFICER_CASE CASCADE CONSTRAINTS;
DROP TABLE CASE_RECORD CASCADE CONSTRAINTS;
DROP TABLE FIR_CRIMINAL CASCADE CONSTRAINTS;
DROP TABLE FIR CASCADE CONSTRAINTS;
DROP TABLE CRIMINAL CASCADE CONSTRAINTS;
DROP TABLE CRIME_TYPE CASCADE CONSTRAINTS;
DROP TABLE OFFICER CASCADE CONSTRAINTS;

CREATE TABLE CRIME_TYPE (
    crime_type_id NUMBER(4) PRIMARY KEY,
    description VARCHAR2(80) NOT NULL UNIQUE
);

CREATE TABLE CRIMINAL (
    criminal_id NUMBER(6) PRIMARY KEY,
    name VARCHAR2(80) NOT NULL,
    dob DATE,
    gender CHAR(1) CHECK (gender IN ('M','F','O')),
    address VARCHAR2(200),
    id_proof_no VARCHAR2(20) UNIQUE,
    status VARCHAR2(20) DEFAULT 'Active' CHECK (status IN ('Active','Arrested','Absconding','Acquitted','Deceased'))
);

CREATE TABLE OFFICER (
    officer_id NUMBER(6) PRIMARY KEY,
    name VARCHAR2(80) NOT NULL,
    rank VARCHAR2(30) NOT NULL CHECK (rank IN ('Constable','Head Constable','SI','Inspector','DSP','SP','DCP','CP')),
    department VARCHAR2(60) NOT NULL,
    badge_no VARCHAR2(15) UNIQUE,
    phone VARCHAR2(15),
    email VARCHAR2(80),
    join_date  DATE DEFAULT SYSDATE
);

CREATE TABLE FIR (
    fir_id NUMBER(8) PRIMARY KEY,
    crime_type_id NUMBER(4) REFERENCES CRIME_TYPE(crime_type_id),
    date_filed DATE DEFAULT SYSDATE NOT NULL,
    location VARCHAR2(150) NOT NULL,
    description VARCHAR2(500),
    status VARCHAR2(25) DEFAULT 'Pending' CHECK (status IN ('Pending','Under Investigation','Charge Sheeted','Closed'))
);

CREATE TABLE FIR_CRIMINAL (
    fir_id NUMBER(8) REFERENCES FIR(fir_id) ON DELETE CASCADE,
    criminal_id NUMBER(6) REFERENCES CRIMINAL(criminal_id) ON DELETE CASCADE,
    role_in_crime VARCHAR2(50) DEFAULT 'Accused' CHECK (role_in_crime IN ('Accused','Suspect','Accomplice','Witness')),
    PRIMARY KEY (fir_id, criminal_id)
);

CREATE TABLE CASE_RECORD (
    case_id NUMBER(8) PRIMARY KEY,
    fir_id NUMBER(8) REFERENCES FIR(fir_id),
    status VARCHAR2(20) DEFAULT 'Open' CHECK (status IN ('Open','Under Trial','Closed','Cold')),
    start_date DATE DEFAULT SYSDATE,
    close_date DATE
);

CREATE TABLE OFFICER_CASE (
    officer_id NUMBER(6) REFERENCES OFFICER(officer_id),
    case_id NUMBER(8) REFERENCES CASE_RECORD(case_id),
    assignment_date DATE,
    role VARCHAR2(50),
    is_lead CHAR(1) CHECK (is_lead IN ('Y','N')),
    PRIMARY KEY (officer_id, case_id)
);

CREATE TABLE EVIDENCE (
    evidence_id NUMBER PRIMARY KEY,
    case_id NUMBER REFERENCES CASE_RECORD(case_id),
    officer_id NUMBER REFERENCES OFFICER(officer_id),
    type VARCHAR2(20)
        CHECK (type IN ('Physical','Digital','Forensic','Documentary')),
    description VARCHAR2(255),
    evidence_date DATE
);

CREATE TABLE COURT_HEARING (
    hearing_id NUMBER PRIMARY KEY,
    case_id NUMBER REFERENCES CASE_RECORD(case_id),
    hearing_date DATE,
    status VARCHAR2(20),
    remarks VARCHAR2(255)
);
CREATE TABLE SYSTEM_AUDIT_LOG (
    audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_table VARCHAR2(50),
    record_id NUMBER,
    action_type VARCHAR2(50),
    old_value VARCHAR2(255),
    new_value VARCHAR2(255),
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);